### ISSUE TITLE
Deployer tasks aren't creating all of their default values

### ISSUE THREAD

**Issue by David-M-IBM** [cloud-native-toolkit/cdk8s-pipelines-lib#33]
Importing one of our custom tasks like IbmPak03 doesn't fill in with any of its info. It is able to use TaskBuilder methods to add values, but I don't believe this is the intended output of the class.

**What the main.ts section looks like now:**
.withTask(new IbmPak03(this, 'ibm-pak-03-id').withName('random-name'))

**What the generated pipeline yaml looks like now:**
```
- name: ibm-pak-03-id
      taskRef:
        name: random-name
      params: []
      workspaces: []
```

<img width="1360" alt="image" src="https://github.com/cloud-native-toolkit/cdk8s-pipelines-lib/assets/83517881/9ae49bf6-c2ee-41f7-bf47-d31f0d4bce15">

<img width="1273" alt="image" src="https://github.com/cloud-native-toolkit/cdk8s-pipelines-lib/assets/83517881/18e0bffd-1452-493d-83ef-41ef1ca42065">
